name: billy
favicon: null
layout_spectrum: 0.27528936322778463
typography_spectrum: 0.45823612762615085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1570462107192725
  lightness: 0.7828549125697464
  saturation: 0.10154559439979494
  rhythmicContrast: 0.5121949249878526
purpose: []
